name: Improvement
description: Suggest an improvement or enhancement to existing functionality
title: "[Improvement]: "
labels: ["improvement", "enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting an improvement! Please provide details about your suggestion.
    - type: textarea
      id: improvement-description
      attributes:
          label: What would you like to improve?
          description: Describe the current functionality and how it could be better.
          placeholder: The current X feature could be improved by...
      validations:
          required: true
    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: If you have ideas on how to implement this improvement, please share them.
          placeholder: I suggest implementing this by...
      validations:
          required: false
    - type: textarea
      id: alternatives
      attributes:
          label: Alternative Solutions
          description: Have you considered any alternative solutions or workarounds?
          placeholder: Another approach could be...
      validations:
          required: false
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or examples about the improvement.
      validations:
          required: false